### ISSUE TITLE
你好, 我把程序下载下来了, 但是真机调试时候说缺少SDK9.0, 怎么样才能适配IOS7以上呢, 很急, 希望你能联系我, QQ1229521716, 谢谢

### ISSUE THREAD

**Issue by wangjianxue** [AliThink/WechatShortVideo#1]
你好, 我把程序下载下来了, 但是真机调试说缺少IOS9.0, 我想适配IOS7.0以上, 怎么才能解决呢, 很急, 希望你能联系我, QQ1229521617, 谢谢啦

**Comment by AliThink** [comment]
可以尝试使用pod集成，默认是7.0以上的，可能是demo的问题，已经添加你的qq了，具体可以在qq上聊

**Comment by wangjianxue** [comment]
没有收到QQ呢

**Comment by AliThink** [comment]
已经发过两次QQ好友申请了，无响应 >_<|||

**Comment by wangjianxue** [comment]
QQ1229521617重要的事说三遍 哈哈

**Comment by wangjianxue** [comment]
微信nb30282016

**Comment by AliThink** [comment]
还是没有添加成功你的qq >_<||| 关于iOS7的问题也可以参考下 #4

**Comment by wangjianxue** [comment]
晕倒, 微信微信微信, 重要的实情说三遍
