### ISSUE TITLE
一直按住“按住拍”按钮，会出现两个SCVideoPlayerView

### ISSUE THREAD

**Issue by Aster0id** [AliThink/WechatShortVideo#10]
在我一直按钮“按住拍”按钮，并达到最大时长时，会创建两个SCVideoPlayerView。我查了一下原因。因为执行了两次[self cancelCaptureWithSaveFlag:YES]方法。

第一次出现：因为设置了最大拍摄时间 ，所以在达到最大时长时会触发- (void)recorder:(SCRecorder *__nonnull)recorder didCompleteSession:(SCRecordSession *__nonnull)session这个方法，方法中创建了一个SCVideoPlayerView并播放Video。

第二次出现：因为第一次创建（也就是执行- (void)recorder:(SCRecorder *__nonnull)recorder didCompleteSession:(SCRecordSession *__nonnull)session 方法）时，没有对“按住拍”按钮的状态做处理。所以导致执行了一次 - (IBAction)captureStartTouchUpInside:(UIButton *)captureBtn 方法，这里又创建了一个SCVideoPlayerView。

我是这里修改的

```
- (IBAction)captureStartTouchUpInside:(UIButton *)captureBtn {

    //confirm capture
    [self hideMiddleTipView];

   if ([_scanPreviewView viewWithTag:400]) {
        return;
    } 
    if (captureValidFlag) {
        //preview and save video
        [self cancelCaptureWithSaveFlag:YES];
    } else {
        [self cancelCaptureWithSaveFlag:NO];
        [self showCaptureBtn];
    }
}
```

多加了一个[[_scanPreviewView viewWithTag:400]]是否存在的判断，我不知道修改那个属性能最优处理这个问题，望作者修改一下。

**Comment by AliThink** [comment]
^_^确实是个问题，非常感谢，已经在0.1.9版本修正
