### ISSUE TITLE
真机调试，WechatShortVideoController在dismiss的时候，屏幕顶部部分被渲染成红色且视图有较大的跳动

### ISSUE THREAD

**Issue by xiafb** [AliThink/WechatShortVideo#2]
真机调试，WechatShortVideoController在dismiss的时候，屏幕顶部部分被渲染成红色且视图有较大的跳动

**Comment by xiafb** [comment]
如有知道此问题的麻烦帮忙解答下，谢谢！

**Comment by AliThink** [comment]
你好 这是iOS调用摄像API都会有的现象 微信也不例外

**Comment by xiafb** [comment]
同样跑了下SCRecorder，但是没发现同样的问题，不知道是不是做了什么处理？

**Comment by AliThink** [comment]
并没有做什么特别的处理，我跑了一下最新的demo也没有重现该问题，不过之前我确实也注意到这一块

**Comment by xiafb** [comment]
能否加QQ具体请教下，QQ：1138605175， 谢谢啦！

**Comment by xiafb** [comment]
问题已经解决了，谢谢

**Comment by xilin** [comment]
@xiafb 我这现在真机也有这个问题，你是怎么解决的吗？

**Comment by xiafb** [comment]
@xilin 抱歉有私事，几天没开电脑了。我是在viewWillDisappear方法里加了一行代码_recorder = nil;

**Comment by xilin** [comment]
@xiafb 我试了下我这不行。。。看来还要找找原因。谢谢~

**Comment by xilin** [comment]
https://github.com/rFlex/SCRecorder/issues/177 我这里出现的应该这个issue里描述的顶部录音提示红bar，不知道你之前那个是不是这个
