### ISSUE TITLE
iPhone 4s (iOS7.1.2)上崩溃了

### ISSUE THREAD

**Issue by l900416** [AliThink/WechatShortVideo#4]
RT：
Demo在iPhone 4s（iOS7.1.2系统）上崩溃了
----------------------Crash-Log-----------------------
2015-09-25 09:56:43.777 WechatShortVideoDemo[501:60b] **\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'
**\* First throw call stack:
(0x2f75ef83 0x39f0fccf 0x2f75eec5 0x31bf16a3 0x31bf15a7 0x2c5685 0x31fd4941 0x92b63 0x9283d 0x31f7bd59 0x31bf962b 0x31bf4e3b 0x31bf4ccd 0x31bf46df 0x31bf44ef 0x31bee21d 0x2f72a255 0x2f727bf9 0x2f727f3b 0x2f692ebf 0x2f692ca3 0x34598663 0x31fdf14d 0xc4bbd 0x3a41cab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by l900416** [comment]
找到解决办法了
https://github.com/rFlex/SCRecorder/issues/174

这是个很不错的UI哦，😄

**Comment by AliThink** [comment]
感谢你提供的解决方案，有好的想法可以一起完善它 ^_^
