### ISSUE TITLE
修改输出文件名为时间戳 最终返回的时间戳与最终目录的不一致

### ISSUE THREAD

**Issue by HuaZao** [AliThink/WechatShortVideo#9]

**Comment by AliThink** [comment]
猜测你是在宏变量里面写了程序逻辑，执行时间的不同会导致两次结果的不一致

**Comment by HuaZao** [comment]
恩。所以针对要保存多个小视频，这样写宏变量 行不通。。。我直接在源码 定义了一个全局变量就好了

**Comment by HuaZao** [comment]
恩。所以针对要保存多个小视频，这样写宏变量 行不通。。。我直接在源码 定义了一个全局变量就好了

**Comment by AliThink** [comment]
ok，问题解决了就好^_^
